import json,pathlib,hashlib
p=pathlib.Path(__file__).parent;repo=pathlib.Path('/Volumes/madara/2026/Projects/tryambakam-noesis/Selemene-engine')
data='''panchanga|calendar|Date, instant, coordinates, timezone and natal/daily mode|Five limbs including vara|Team|Schedule a shared check-in, then respond to actual circumstances|Daily witness text is natal-worded; timezone semantics need care
human-design|natal|Exact birth date, local time, timezone and coordinates|Type, authority, profile, gates, channels, centers|All four|Make distinct decision processes explicit before allocating work|No compatibility or moral score; internal consistency is not independent chart certification
gene-keys|contemplative|Birth inputs or explicit HD gates|Activation keys and interpretive sequences|Corv; Jian; all|Recognize a familiar pattern and choose a different response|Default line 3 and confirmed label mismatches quarantined
vimshottari|long-period timing|Birth inputs and evaluation instant|Nested planetary periods and transitions|All four|Revisit an old response under a different proposed period|Structured nesting only; periods do not cause or excuse conduct
numerology|symbolic identity|Name and birth date; system choice|Name/date reductions and themes|Corv|Ask how an inherited name-story shapes a present choice|Symbolic arithmetic is not an objective personality diagnosis
biorhythm|calculated cycle|Birth date and target date|23/28/33-day sine cycles|Jian|Compare an expectation with a lived observation and preserve disagreement|Not measured physiology or prana
vedic-clock|traditional time map|Instant plus explicit timezone offset or supported timezone|Local hour, dosha, organ-clock correspondence|Team; Gideon|Make space for food, rest and a check-in in ordinary work|Traditional correspondence; no medical or performance guarantee
biofield|birth-derived symbolic map|Birth inputs and target instant|Planet-chakra mappings and derived metrics|Sona; Gideon|Use a map as a question, then listen and adjust the real interaction|Vedic backend is not a camera capture or measured bodily field; is_mock=false is insufficient
biofield-capture|media-derived analysis|Actual capture, consent and quality; sidecar availability|Capture analysis and persisted readings via dedicated workflow|Jian; Sona|Compare a repeat capture with self-report and environmental changes|No fictional fixture should masquerade as a physical measurement; not live exercised
face-reading|image/heuristic interpretation|Consented image for CV path; birth and heuristic fallbacks exist|Landmark/zone mapping plus traditional interpretations|Gideon; Corv|Notice an interpretation forming, ask the person, revise the assumption|Do not infer moral character, health, trustworthiness or destiny from facial appearance; non-mock can still mean heuristic
nadabrahman|sound recommendation|Instant, optional dosha, rasa/mood, chakra|Ranked Melakarta recommendations and note patterns|Sona|Listen, choose a candidate phrase, ask permission, observe response|Inspected implementation recommends; it does not substantiate advertised vocal analysis; UTC hour issue
raaga|musical structure|Explicit Melakarta 1–72 or name, root Hz, optional clip request|Swaras, ratios, ascending/descending indices and optional audio|Sona|Try a short phrase and alter pacing or stop in response to the listener|Auto-time uses wall clock; use explicit Melakarta. Therapeutic labels are not demonstrated effects
tarot|symbolic inquiry|Question/spread or birth-card mode and recorded seed/options|Cards and interpretive prompts|Corv|Consider a neglected possibility before a real conversation|A draw cannot establish future events; freeze draw/seed, do not reroll for plot convenience
i-ching|symbolic change|Question, explicit hexagram or seed/casting inputs|Primary/relating hexagrams and changing lines|Jian; Corv|Hold a transition question while testing an actual decision|Inspected implementation supports seeded selection; do not imply physical casting or prediction
 enneagram|self-pattern lookup|Existing type or assessment inputs, retained with provenance|Type themes and prompts|All four|Notice motive, own harm, practise another response|Current four results were seeded by existing canon, not independently discovered
sacred-geometry|visual contemplation|Explicit form, intention and optional template|Geometric symbolism and visual guidance|Jian|Use a diagram to communicate a boundary, then test whether it is usable|Geometry does not establish energetic causation; preserve selected form
sigil-forge|intention artifact|Intention, method/style, optional generation settings|Reduced intention/guidance and optional image|Gideon; Corv|Attach an intention to a concrete repeatable act and check follow-through|A symbol is not a substitute for action; do not claim an ungenerated image exists
transits|current planetary context|Birth inputs and target instant|Sidereal positions, aspects and Sade Sati context|All four|Compare a timing interpretation with actual conditions before choosing|Not a prediction of conduct or a substitute for observed consequences
financial-biosensor|composite decision reflection|Birth data, target instant, optional actual biometric sample|Five-engine composition and contributor provenance|Gideon; Jian|Consider resource allocation and who bears a decision's cost|Not a financial forecast, trade instruction or prana meter; inherits upstream GK limitations'''
rows=[];infos={r['body']['engine_id']:r for r in json.loads((p/'live-engine-info.json').read_text()) if 'engine_id' in r.get('body',{})}
for line in data.splitlines():
 e,kind,inputs,outputs,characters,action,limit=line.split('|');e=e.strip();receipts=sorted(str(x.relative_to(p)) for x in (p/'engine-runs').glob(f'*-{e}-*.json'))
 rows.append({'id':e,'category':kind,'inputs_to_freeze':inputs,'output_scope':outputs,'character_focus':characters,'proposed_outward_action':action,'limits':limit,'live_info_status':infos[e]['status'],'required_phase':infos[e]['body']['required_phase'],'calculate_endpoint':f'/api/v1/engines/{e}/calculate','calculation_receipts':receipts,'calculation_status':'receipts available; see field-level quality limits' if receipts else 'not exercised; reviewed metadata/source contract'})
assert len(rows)==19 and set(r['id'] for r in rows)==set(infos)
endpoints=[
('Selemene','POST','/api/v1/witness/interpret','Birth/partner context plus required live_scores; returns Aletheios, Pichet, synthesis, witness_question, engines_used, llm_powered','Source uses Utc::now, no story as_of parameter; seven primary engines, four partner engines; partial failures tolerated. Do not fabricate live_scores. Not invoked.'),
('Selemene','POST','/api/v1/assets/generate','Mode, report_level L0–L5, subjects/locations and relationship context; passes, assembled text and source_pack','Inspected Rust route renders seed text; not full LLM report pipeline. Uses now and focused six-engine primary-subject seeds. Not invoked.'),
('Selemene','GET','/api/v1/readings','Reading history; /stats and /:reading_id variants','Source route review only; unrelated user readings were not fetched.'),
('Selemene','GET','/api/v1/raga/:num/clip','Existing clip lookup','Source route review only; a musical profile receipt is not an audio clip.'),
('Selemene','POST','/api/v1/biofield/sessions','Create capture session; /:id/captures, /:id/close; readings, baselines and exports','Source workflow review; requires genuine capture inputs and storage proof.'),
('selemene-gw','GET','/health','Version and KV key-presence booleans','Source only; KV values not read.'),
('selemene-gw','ALL','/api/v1/*','Owner bearer authenticated proxy; injects upstream key from SELEMENE_SECRETS','KV stores gateway credentials, not the character canon. Deployment not verified here.'),
('pattern-memory worker','POST','/patterns','Upsert extracted patterns to embeddings and durable storage','Source entrypoint has no auth gate; deployment and outer protection unverified. No writes performed.'),
('pattern-memory worker','POST','/patterns/query','Retrieve by query, filters and limit','Source only; binding placeholders are not deployed endpoint evidence.'),
('pattern-memory worker','GET','/','Name/version','Source only.'),
('llm-proxy worker','POST','provider proxy request','Shared-secret gate then KV-backed provider routing','No general public KV CRUD endpoint established; reviewed source only.')]
obj={'schema_version':'1.0.0','status':'review-complete registry; proposed mappings; dates NOT frozen; final character reports pending date freeze and listed contract fixes','source_head':'9a05f5cc90777f083d7065e491484ef727aeada1','engines':rows,'endpoints':[dict(zip(['surface','method','path','purpose','evidence_limit'],x)) for x in endpoints],'somatic_layer':{'engine_id':None,'status':'proposed practice layer; no standalone somatic engine in live 19-engine inventory','sequence':['notice embodied experience','choose a contextual lens','try a consensual bounded outward action','observe effect and disagreement','repair or adjust','repeat in ordinary life'],'nada_raaga_receipts':['engine-runs/team-nadabrahman-book1.json','engine-runs/sona-raaga-book1.json'],'not_claimed':['automatic bodily diagnosis','guaranteed resonance','clinical healing','literal reality alteration']},'freeze_contract':{'status':'not_frozen','required':['birth local date/time/timezone/coordinates and calendar convention','chapter event instants and location/timezone','source and engine versions','explicit symbolic draw seeds or chosen forms','media provenance where applicable','actual report implementation/provider/model and fallback status','field-level quality exclusions','human review of interpretation and canon promotion'],'replay_policy':'Change an input => new revision/hash and new dependent calculations. Preserve prior receipts; do not overwrite them or reroll to obtain a preferred result.'},'sources':[]}
for f in ['crates/noesis-api/src/lib.rs','crates/noesis-api/src/handlers/witness.rs','crates/noesis-api/src/handlers/assets.rs','crates/engine-nadabrahman/src/engine.rs','ts-engines/src/engines/raaga/engine.ts','crates/engine-face-reading/src/engine.rs','crates/engine-biofield/src/engine.rs','crates/engine-financial-biosensor/src/engine.rs','packages/witness-pipeline/src/orchestrator/integrated.ts','workers/pattern-memory/src/index.ts','workers/pattern-memory/src/patterns/cloudflare-vectorize-lite.ts','workers/selemene-gw/src/index.js','workers/llm-proxy/src/index.ts']:
 file=repo/f;obj['sources'].append({'path':str(file),'sha256':hashlib.sha256(file.read_bytes()).hexdigest()})
(p/'engine-integration-registry.json').write_text(json.dumps(obj,indent=2)+'\n')
md=['# All-engine integration review','','All 19 live engine info endpoints returned HTTP 200. Six workflows are listed; full-spectrum still advertises 17 engines, so its name does not establish coverage of the 19-engine inventory. JSON source of this review: [engine-integration-registry.json](engine-integration-registry.json). Source docs/ENGINES.md also says 17 and overstates some media capabilities; runtime inventory and inspected implementation take precedence.','','| Engine | Story use in the real-world-facing action | Boundary |','|---|---|---|']
md.extend(f"| {r['id']} | {r['proposed_outward_action']} | {r['limits']} |" for r in rows)
(p/'ALL-ENGINES.md').write_text('\n'.join(md)+'\n')
