from pathlib import Path
import json,collections,hashlib
p=Path(__file__).parent
chars=[('corv',9,1,'The wish for harmony can close a question too early.','Leaves disagreement open rather than securing assent.','sw:enn:9:core'),('sona',4,7,'Felt relief may become evidence for a desired identity.','Makes the missed trace available for another person to mark.','sw:enn:4:core'),('jian',5,6,'Competence can become a reason to keep control of information.','Shares his second scanner view and asks where Sona would start.','sw:enn:5:core'),('gideon',8,3,'Protection can become control when only the protector defines safety.','Waits for Sona to test her reach before fixing the span he would cover.','sw:enn:8:core')]
records=[]
for c,t,ch,q,action,seed in chars:
 records.append(dict(character=c,selected_enneagram=t,context_record=seed,report_context=f'reports/{c}-integrated-reading.json',question=q,chapter=ch,authored_action=action,status='REVIEWED_EDITORIAL_PROPOSAL',boundary='Neither lookup nor generated reading establishes an inevitable trait; scene evidence and consequences govern interpretation.',engine_access='shared repertoire; selection follows context',feedback='Another person may correct, decline, disagree, or test the proposed action.'))
reject=[{'report':'sona-integrated-reading','location':'line 237','claim':'Design Earth 31.2 and personality Sun 33.5','reason':'Frozen source gives design Jupiter 31.2, personality Jupiter 33.5, design Earth 6.6 and personality Sun 12.4.','disposition':'EXCLUDE'}, {'report':'sona-integrated-reading','location':'lines 257,303','claim':'Gate 3 completes 59-6; Sacral-Throat connection','reason':'Unsupported by supplied two-channel split; do not invent circuitry.','disposition':'EXCLUDE'},{'report':'sona-integrated-reading','location':'line 262','claim':'Body literally cannot move as fast','reason':'Symbolic biorhythm provides no physiological evidence.','disposition':'EXCLUDE'},{'report':'sona-integrated-reading','location':'structural field','claim':'Independent systems confirm non-negotiable emotional sequencing and need others to feel whole','reason':'Interpretive agreement is not independent validation; waiting is contextual, and split definition is not personal incompleteness.','disposition':'EXCLUDE'}]
(p/'reviewed-mapping.json').write_text(json.dumps({'version':1,'state':'DRAFT_CONTEXT_ONLY','characters':records,'rejected_generated_claims':reject,'retrieval':{'exact_records':10,'similarity_queries':4,'similarity_matches':0,'inspected_kv_namespaces':['ENGINE_DATA','CONSCIOUSNESS_KV'],'kv_keys':0,'fresh_embedding_http_status':410},'engine_inputs_changed':False,'remote_writes':False,'full_report_fact_check':False,'review_scope':'Selective interpretation review and concrete new prose; raw reports remain unreviewed context, not validated charts or canon.'},indent=2)+'\n')
reports=list((p/'reports').glob('*.json'));calls=[json.loads(f.read_text()) for f in (p/'calls').glob('*.json')];rubrics=[x['rubric'] for f in reports for x in json.loads(f.read_text())['output']['passes']]
integrity=[{'report':f.stem,'output_limited_passes':[c['pass_index'] for c in calls if c['job']==f.stem and c.get('finish_reason')=='length'],'status':'CONTEXT_ONLY_NOT_VALIDATED'} for f in reports]
receipt={'report_integrity':integrity,'reports_generated':len(reports),'passes_completed':len(calls),'models_returned':dict(collections.Counter(c['returned_model'] for c in calls)),'finish_reasons':dict(collections.Counter(c.get('finish_reason') for c in calls)),'rubric_word_count_fit':dict(collections.Counter(r['word_count_fit'] for r in rubrics)),'rubric_guardrail_gate':dict(collections.Counter(r['guardrail_gate'] for r in rubrics)),'rubric_fact_gate':dict(collections.Counter(r['deterministic_fact_gate'] for r in rubrics)),'report_state':'CONTEXT_ONLY; not all prose fact checked','reviewed_mapping':'reviewed-mapping.json','patterns_remote_upserted':0,'source_report_sha256':{f.name:hashlib.sha256(f.read_bytes()).hexdigest() for f in reports}}
(p/'verification.json').write_text(json.dumps(receipt,indent=2)+'\n');print(json.dumps({k:v for k,v in receipt.items() if k!='source_report_sha256'},indent=2))
