#!/usr/bin/env python3
"""nigredo.py — Nigredo detection phase of the Ether-First Alchemical Autoresearch Loop.

Nigredo ("the blackening") is the decomposition pass: it scans source text and
surfaces the spots where an ether-first manifest has been contaminated by
matter-first framing, categorical leaks, unsupported substrate-level claims,
and internal contradictions.

Self-contained: pure standard library, fully deterministic, no NLP packages.
Sibling contracts honoured:

  - schemas.py: Finding{kind, detail, phase}; kind in
    {CATEGORICAL-LEAK, MATTER-FIRST-FRAMING, UNSUPPORTED-CLAIM, CONTRADICTION};
    run_nigredo() emits plain dicts with those keys so it interoperates with
    or without schemas.py present.
  - phases.py: check_ether_first() / DEFAULT_MATTER_FIRST_MARKERS — the
    default marker list below matches that contract.

All functions are pure: same input, same output, no I/O, no clocks, no RNG.
"""

from __future__ import annotations

import re
from typing import Dict, Iterable, List, Optional, Sequence, Set, Tuple

PHASE = "NIGREDO"

KIND_MATTER_FIRST = "MATTER-FIRST-FRAMING"
KIND_CATEGORICAL_LEAK = "CATEGORICAL-LEAK"
KIND_UNSUPPORTED_CLAIM = "UNSUPPORTED-CLAIM"
KIND_CONTRADICTION = "CONTRADICTION"

Span = Tuple[int, int]

# ---------------------------------------------------------------------------
# Default vocabularies (deterministic, lowercase matching)
# ---------------------------------------------------------------------------

# Mirrors phases.DEFAULT_MATTER_FIRST_MARKERS: phrases that frame matter as
# the generator/substrate of consciousness or field-level phenomena.
DEFAULT_MATTER_FIRST_MARKERS: Tuple[str, ...] = (
    "the brain generates",
    "the brain creates",
    "the brain produces",
    "neural correlates produce",
    "neural activity generates",
    "neurons give rise to",
    "matter gives rise to",
    "matter produces consciousness",
    "consciousness emerges from matter",
    "consciousness arises from matter",
    "consciousness is a product of the brain",
    "consciousness is generated by the brain",
    "the mind is what the brain does",
    "mind is a product of brain",
    "the physical world is all there is",
    "consciousness is an emergent property of matter",
)

# Field-level (claimed primary/substrate) terms — the X in "X is just Y".
FIELD_LEVEL_TERMS: Tuple[str, ...] = (
    "consciousness",
    "awareness",
    "field",
    "soul",
    "spirit",
    "mind",
    "prana",
    "ether",
    "substrate",
    "energy",
    "information",
)

# Matter-level (derived/reductive) terms — the Y in "X is just Y".
MATTER_LEVEL_TERMS: Tuple[str, ...] = (
    "brain",
    "neurons",
    "neural activity",
    "matter",
    "chemistry",
    "chemical reactions",
    "physics",
    "atoms",
    "molecules",
    "electromagnetic fields",
    "electromagnetism",
    "the body",
    "physical processes",
    "particles",
    "synapses",
)

# Assertion verbs that claim substrate-level establishment of fact.
ASSERTION_VERBS: Tuple[str, ...] = (
    "proves",
    "prove",
    "demonstrates",
    "demonstrate",
    "establishes",
    "establish",
    "shows that",
    "show that",
    "confirms",
    "confirm",
)

# Reduction copulas: "X is [just/only/nothing but/merely/simply] Y".
_REDUCTION_ADVERBS = (
    "just",
    "only",
    "nothing but",
    "merely",
    "simply",
    "really",
    "ultimately",
    "basically",
    "essentially",
)

# ---------------------------------------------------------------------------
# Text utilities
# ---------------------------------------------------------------------------

_SENTENCE_SPLIT_RE = re.compile(r"(?<=[.!?])\s+")
_WORD_RE = re.compile(r"[a-z][a-z'-]*")


def _sentences_with_spans(text: str) -> List[Tuple[str, Span]]:
    """Split text into (sentence, (start, end)) pairs via simple regex."""
    out: List[Tuple[str, Span]] = []
    start = 0
    for chunk in _SENTENCE_SPLIT_RE.split(text):
        idx = text.find(chunk, start)
        if idx < 0:
            idx = start
        stripped = chunk.strip()
        if stripped:
            lead = len(chunk) - len(chunk.lstrip())
            s = idx + lead
            out.append((stripped, (s, s + len(stripped))))
        start = idx + len(chunk)
    return out


def _find_phrase_spans(haystack: str, needle: str) -> List[Span]:
    """All [start, end) spans of `needle` in `haystack` (both already lowered)."""
    spans: List[Span] = []
    start = 0
    while True:
        i = haystack.find(needle, start)
        if i < 0:
            break
        spans.append((i, i + len(needle)))
        start = i + len(needle)
    return spans


def _tokens(text: str) -> Set[str]:
    return set(_WORD_RE.findall(text.lower()))


def _has_phrase(lowered: str, phrase: str) -> bool:
    """Whole-phrase containment with non-word boundaries."""
    pattern = r"(?<![\w])" + re.escape(phrase) + r"(?![\w])"
    return re.search(pattern, lowered) is not None

# ---------------------------------------------------------------------------
# (1) Matter-first framing
# ---------------------------------------------------------------------------

def detect_matter_first(
    text: str,
    markers: Optional[Sequence[str]] = None,
) -> List[Tuple[Span, str]]:
    """Return [(span, marker)] for each matter-first marker phrase occurrence.

    Matching is case-insensitive; `markers` is configurable and defaults to
    DEFAULT_MATTER_FIRST_MARKERS (aligned with phases.py).
    """
    if markers is None:
        markers = DEFAULT_MATTER_FIRST_MARKERS
    lowered = text.lower()
    findings: List[Tuple[Span, str]] = []
    for marker in markers:
        needle = marker.lower()
        pattern = r"(?<![\w])" + re.escape(needle) + r"(?![\w])"
        for match in re.finditer(pattern, lowered):
            findings.append((match.span(), marker))
    findings.sort(key=lambda item: item[0])
    return findings

# ---------------------------------------------------------------------------
# (2) Categorical leaks
# ---------------------------------------------------------------------------

def _build_reduction_re() -> re.Pattern:
    field_group = "|".join(re.escape(term) for term in
                           sorted(FIELD_LEVEL_TERMS, key=len, reverse=True))
    matter_group = "|".join(re.escape(term) for term in
                            sorted(MATTER_LEVEL_TERMS, key=len, reverse=True))
    adverb_group = "|".join(re.escape(a) for a in
                            sorted(_REDUCTION_ADVERBS, key=len, reverse=True))
    # "X is [just/only/nothing but/...] Y" where X is field-level, Y matter-level.
    pattern = (
        r"\b(?P<field>" + field_group + r")\b"
        r"\s+(?:is|are|was|were)\s+"
        r"(?:(?:" + adverb_group + r")\s+)?"
        r"(?P<matter>" + matter_group + r")\b"
    )
    return re.compile(pattern, re.IGNORECASE)

_REDUCTION_RE = _build_reduction_re()


def detect_categorical_leaks(text: str) -> List[Tuple[Span, Tuple[str, str]]]:
    """Return [(span, (field_term, matter_term))] reduction-pattern leaks.

    A categorical leak treats a field-level phenomenon (X) as identical to a
    derived matter-level phenomenon (Y): "consciousness is just neurons
    firing", "energy is matter", "the soul is the body".
    """
    findings: List[Tuple[Span, Tuple[str, str]]] = []
    for match in _REDUCTION_RE.finditer(text):
        field_term = match.group("field").lower()
        matter_term = match.group("matter").lower()
        # Require the reduction to actually collapse X into Y: either an
        # adverbial reducer is present, or the copula directly equates the
        # two levels ("energy is matter"). Both forms are leaks; adverbless
        # forms of "X is Y" between levels are still category errors.
        findings.append((match.span(), (field_term, matter_term)))
    findings.sort(key=lambda item: item[0])
    return findings

# ---------------------------------------------------------------------------
# (3) Unsupported claims
# ---------------------------------------------------------------------------

def detect_unsupported_claims(
    text: str,
    manifest_terms: Set[str],
) -> List[Span]:
    """Return [span] of sentences asserting substrate-level facts with no
    provenance anchor.

    A sentence is an unsupported claim when it contains an assertion verb
    (proves / demonstrates / establishes / shows that / confirms) AND a
    substrate-level subject, but references NO term from `manifest_terms`
    (the manifest vocabulary that anchors claims to prior provenance).
    """
    manifest = {term.lower() for term in manifest_terms}
    spans: List[Span] = []
    for sentence, span in _sentences_with_spans(text):
        lowered = sentence.lower()
        has_assertion = any(_has_phrase(lowered, verb) for verb in ASSERTION_VERBS)
        if not has_assertion:
            continue
        sentence_tokens = _tokens(sentence)
        has_anchor = any(
            term in sentence_tokens or _has_phrase(lowered, term)
            for term in manifest
        )
        if not has_anchor:
            spans.append(span)
    return spans

# ---------------------------------------------------------------------------
# (4) Contradictions
# ---------------------------------------------------------------------------

_IS_STATEMENT_RE = re.compile(
    r"\b(?P<subject>[A-Za-z][A-Za-z' -]{0,60}?)\s+"
    r"(?P<neg>is\s+not|isn't|are\s+not|aren't|was\s+not|wasn't|were\s+not|weren't|is|are|was|were)\s+"
    r"(?P<predicate>[A-Za-z][A-Za-z' -]{0,60}?)(?=[.,;:!?)]|$)",
    re.IGNORECASE,
)

_METRIC_RE = re.compile(
    r"\b(?P<metric>[A-Za-z][A-Za-z -]{1,40}?)\s*"
    r"(?:of|is|was|are|were|equals|=|:)?\s*"
    r"(?P<value>\d+(?:\.\d+)?)\s*"
    r"(?P<unit>%|hz|khz|mhz|ghz|ms|s|mm|cm|m|km|kg|g|mg|ev|kev|mev|db|k|nm|μm|um|degrees?)?\b",
    re.IGNORECASE,
)

_UNIT_NORMALIZE = {
    "degree": "degrees",
    "um": "μm",
}


def _is_negative(copula: str) -> bool:
    return "not" in copula.lower() or "n't" in copula.lower()


def _normalize_phrase(phrase: str) -> str:
    return " ".join(phrase.lower().split())


def detect_contradictions(text: str) -> List[Tuple[Span, Span, str]]:
    """Cheap deterministic contradiction heuristics.

    Two detectors:
      a) Predicate polarity — sentence A asserts "X is Y", sentence B asserts
         "X is not Y" (same normalized subject+predicate, opposite polarity).
      b) Numeric — the same metric name appears with different values in the
         same document (unit-normalized comparison).

    Returns [(span_a, span_b, note)].
    """
    sentences = _sentences_with_spans(text)
    contradictions: List[Tuple[Span, Span, str]] = []

    # (a) predicate polarity
    statements: List[Tuple[str, str, bool, Span]] = []
    for sentence, span in sentences:
        for match in _IS_STATEMENT_RE.finditer(sentence):
            subject = _normalize_phrase(match.group("subject"))
            predicate = _normalize_phrase(match.group("predicate"))
            if not subject or not predicate:
                continue
            neg = _is_negative(match.group("neg"))
            abs_span = (span[0] + match.start(), span[0] + match.end())
            statements.append((subject, predicate, neg, abs_span))

    seen_pairs: Set[Tuple[str, str, Span, Span]] = set()
    for i in range(len(statements)):
        for j in range(i + 1, len(statements)):
            subj_a, pred_a, neg_a, span_a = statements[i]
            subj_b, pred_b, neg_b, span_b = statements[j]
            if subj_a == subj_b and pred_a == pred_b and neg_a != neg_b:
                key = (subj_a, pred_a, span_a, span_b)
                if key in seen_pairs:
                    continue
                seen_pairs.add(key)
                note = (
                    "polarity contradiction: '%s is %s' asserted both ways"
                    % (subj_a, pred_a)
                )
                contradictions.append((span_a, span_b, note))

    # (b) numeric contradictions for the same metric
    metrics: Dict[Tuple[str, str], List[Tuple[str, Span]]] = {}
    for sentence, span in sentences:
        for match in _METRIC_RE.finditer(sentence):
            metric = _normalize_phrase(match.group("metric"))
            value = match.group("value")
            unit = (match.group("unit") or "").lower()
            unit = _UNIT_NORMALIZE.get(unit, unit)
            if not metric or len(metric) < 3:
                continue
            abs_span = (span[0] + match.start(), span[0] + match.end())
            metrics.setdefault((metric, unit), []).append((value, abs_span))

    for (metric, unit), occurrences in metrics.items():
        values = {value for value, _ in occurrences}
        if len(values) <= 1:
            continue
        for i in range(len(occurrences)):
            for j in range(i + 1, len(occurrences)):
                value_a, span_a = occurrences[i]
                value_b, span_b = occurrences[j]
                if value_a == value_b:
                    continue
                note = (
                    "numeric contradiction: metric '%s' reported as %s%s and %s%s"
                    % (metric, value_a, unit, value_b, unit)
                )
                contradictions.append((span_a, span_b, note))

    contradictions.sort(key=lambda item: (item[0], item[1]))
    return contradictions

# ---------------------------------------------------------------------------
# (5) Top-level orchestration
# ---------------------------------------------------------------------------

def run_nigredo(
    text: str,
    manifest_terms: Optional[Iterable[str]] = None,
    matter_first_markers: Optional[Sequence[str]] = None,
) -> List[Dict[str, object]]:
    """Run all Nigredo detectors and return findings as plain dicts.

    Each finding: {"kind": <KIND-*>, "detail": <str>, "phase": "NIGREDO",
    "span": (start, end)}. Contradictions additionally carry "span_b" and
    "note". Output shape matches schemas.Finding keys so it composes with or
    without schemas.py.
    """
    manifest = set(manifest_terms) if manifest_terms else set()
    findings: List[Dict[str, object]] = []

    for span, marker in detect_matter_first(text, markers=matter_first_markers):
        findings.append({
            "kind": KIND_MATTER_FIRST,
            "detail": "matter-first framing: '%s' frames matter as the generator" % marker,
            "phase": PHASE,
            "span": span,
            "marker": marker,
        })

    for span, (field_term, matter_term) in detect_categorical_leaks(text):
        findings.append({
            "kind": KIND_CATEGORICAL_LEAK,
            "detail": (
                "categorical leak: field-level '%s' reduced to matter-level '%s'"
                % (field_term, matter_term)
            ),
            "phase": PHASE,
            "span": span,
            "category_pair": (field_term, matter_term),
        })

    for span in detect_unsupported_claims(text, manifest):
        snippet = text[span[0]:span[1]]
        findings.append({
            "kind": KIND_UNSUPPORTED_CLAIM,
            "detail": (
                "unsupported claim: assertion with no manifest-vocabulary anchor: %r"
                % snippet
            ),
            "phase": PHASE,
            "span": span,
        })

    for span_a, span_b, note in detect_contradictions(text):
        findings.append({
            "kind": KIND_CONTRADICTION,
            "detail": note,
            "phase": PHASE,
            "span": span_a,
            "span_b": span_b,
            "note": note,
        })

    findings.sort(key=lambda f: (f["span"], str(f["kind"])))  # type: ignore[index]
    return findings

# ---------------------------------------------------------------------------
# (7) Demo
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    SAMPLE = (
        "The brain generates consciousness. "
        "Consciousness is just neurons firing. "
        "Studies prove the substrate is neural. "
        "The field is primary. "
        "The field is not primary. "
        "Resonance frequency is 432 Hz. "
        "Resonance frequency is 528 Hz. "
        "The etheric body resonates at 432 Hz."
    )

    manifest = {"etheric", "resonates", "resonance"}

    results = run_nigredo(SAMPLE, manifest_terms=manifest)

    print("=" * 72)
    print("NIGREDO — Ether-First Alchemical Autoresearch Loop (demo)")
    print("=" * 72)
    print("Source text:")
    print("  " + SAMPLE)
    print()
    print("Manifest terms:", sorted(manifest))
    print()
    print("Findings (%d):" % len(results))
    for finding in results:
        span = finding["span"]
        line = "  [%s] span=%s" % (finding["kind"], span)
        if "span_b" in finding:
            line += " vs span_b=%s" % (finding["span_b"],)
        print(line)
        print("      %s" % finding["detail"])
    print()

    # Success-criteria self-check.
    required = {
        KIND_MATTER_FIRST: "The brain generates consciousness.",
        KIND_CATEGORICAL_LEAK: "Consciousness is just neurons firing.",
        KIND_UNSUPPORTED_CLAIM: "Studies prove the substrate is neural.",
        KIND_CONTRADICTION: "The field is primary. / The field is not primary.",
    }
    counts: Dict[str, int] = {}
    for finding in results:
        kind = str(finding["kind"])
        counts[kind] = counts.get(kind, 0) + 1

    ok = True
    print("Self-check against success criteria:")
    for kind, example in required.items():
        n = counts.get(kind, 0)
        status = "OK  " if n >= 1 else "FAIL"
        if n < 1:
            ok = False
        print("  [%s] %-22s x%d  (e.g. %s)" % (status, kind, n, example))
    print()
    print("RESULT:", "PASS" if ok else "FAIL")
