"""
rubedo.py — Rubedo acceptance phase of the Ether-First Alchemical Autoresearch Loop.

Consumes synthesis candidates and consequence reports (produced by citrinitas.py),
applies deterministic ACCEPT / REJECT / DEFER gates, and emits a convergence
report. Canon is NEVER mutated by this module — `canon_mutated` is always False
and no write path to canon exists here.

Pure functions. Deterministic. Stdlib only. Python 3.
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional, Sequence

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

FIELD_TAGS = {"DERIVED-FROM-FIELD", "FIELD-FACET"}
MATTER_FIRST_TAG = "MATTER-FIRST-ARTIFACT"

DECISION_ACCEPT = "ACCEPT"
DECISION_REJECT = "REJECT"
DECISION_DEFER = "DEFER"

DEFAULT_ACCEPT_THRESHOLD = 0.8
DEFAULT_REJECT_THRESHOLD = 0.2
MIN_MEMBER_COUNT = 2
MAX_TENSIONS_FOR_NONREJECT = 3

# Phrases that signal a matter-first derivation direction — a candidate whose
# statement derives the field FROM matter violates the ether-first ordering and
# can never be accepted (only deferred for investigation).
MATTER_FIRST_MARKERS: Sequence[str] = (
    "field derives from matter",
    "field emerges from matter",
    "field arises from matter",
    "field is produced by matter",
    "field is generated by matter",
    "field comes from matter",
    "field originates in matter",
    "field is a byproduct of matter",
    "field is an epiphenomenon of matter",
    "matter produces the field",
    "matter generates the field",
    "matter creates the field",
    "matter gives rise to the field",
    "matter gives rise to field",
    "from matter arises the field",
    "field from matter",
)

STOP_REASON_CYCLE_LIMIT = "cycle_limit_reached"
STOP_REASON_CONVERGED = "converged"
STOP_REASON_EXHAUSTED = "candidates_exhausted"
STOP_REASON_MANUAL = "manual_stop"


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _statement_text(candidate: Dict[str, Any]) -> str:
    """Lowercased concatenation of statement + provenance for keyword checks."""
    statement = str(candidate.get("statement", ""))
    provenance = candidate.get("provenance", [])
    if isinstance(provenance, str):
        provenance = [provenance]
    prov_text = " ".join(str(item) for item in provenance)
    return (statement + " " + prov_text).lower()


def _significant_terms(text: str) -> set:
    """Significant terms: alphabetic tokens of length >= 5, lowercased."""
    terms = set()
    token = []
    for char in text.lower():
        if char.isalpha():
            token.append(char)
        else:
            if len(token) >= 5:
                terms.add("".join(token))
            token = []
    if len(token) >= 5:
        terms.add("".join(token))
    return terms


# ---------------------------------------------------------------------------
# (3) Field-grounding probe
# ---------------------------------------------------------------------------

def field_grounding_probe(candidate: Dict[str, Any]) -> Dict[str, Any]:
    """
    Determine whether a candidate is field-grounded.

    A candidate is field-grounded iff:
      - tag is DERIVED-FROM-FIELD or FIELD-FACET, AND
      - provenance is non-empty, AND
      - statement does not derive field FROM matter (no matter-first markers).

    Returns {'grounded': bool, 'reason': str} — deterministic one-line reason.
    """
    tag = candidate.get("tag")
    provenance = candidate.get("provenance")
    statement = str(candidate.get("statement", "")).lower()

    if tag == MATTER_FIRST_TAG:
        return {
            "grounded": False,
            "reason": "tag MATTER-FIRST-ARTIFACT is not a field tag — "
                      "defer-for-investigation, never accept",
        }

    if tag not in FIELD_TAGS:
        return {
            "grounded": False,
            "reason": f"tag {tag!r} not in {sorted(FIELD_TAGS)}",
        }

    if not provenance:
        return {
            "grounded": False,
            "reason": "provenance is empty — no grounding source recorded",
        }

    for marker in MATTER_FIRST_MARKERS:
        if marker in statement:
            return {
                "grounded": False,
                "reason": f"statement contains matter-first marker: {marker!r}",
            }

    return {
        "grounded": True,
        "reason": "field-tagged, provenance non-empty, no matter-first markers",
    }


# ---------------------------------------------------------------------------
# (4) ISA probe
# ---------------------------------------------------------------------------

def isa_probe(candidate: Dict[str, Any], isa_criteria: List[str]) -> Dict[str, Any]:
    """
    Deterministic keyword check of candidate against ISA criteria.

    A criterion is satisfied iff it shares >= 1 significant term (len >= 5)
    with the candidate's statement + provenance text.

    Returns {'satisfies': [...], 'misses': [...]}.
    """
    candidate_terms = _significant_terms(_statement_text(candidate))

    satisfies: List[str] = []
    misses: List[str] = []

    for criterion in isa_criteria:
        criterion_terms = _significant_terms(criterion)
        if candidate_terms & criterion_terms:
            satisfies.append(criterion)
        else:
            misses.append(criterion)

    return {"satisfies": satisfies, "misses": misses}


# ---------------------------------------------------------------------------
# (1) ACCEPT / REJECT / DEFER gates
# ---------------------------------------------------------------------------

def accept_candidate(
    candidate: Dict[str, Any],
    report: Dict[str, Any],
    thresholds: Optional[Dict[str, float]] = None,
) -> bool:
    """
    ACCEPT gate — all conditions must hold:

      - grounding_score >= accept_threshold (default 0.8)
      - report.consistent is True
      - member_count >= 2
      - tag in {DERIVED-FROM-FIELD, FIELD-FACET}

    MATTER-FIRST-ARTIFACT candidates can never be accepted.
    """
    thresholds = thresholds or {}
    accept_threshold = thresholds.get("accept", DEFAULT_ACCEPT_THRESHOLD)

    if candidate.get("tag") == MATTER_FIRST_TAG:
        return False

    if candidate.get("tag") not in FIELD_TAGS:
        return False

    if report.get("grounding_score", 0.0) < accept_threshold:
        return False

    if report.get("consistent") is not True:
        return False

    if candidate.get("member_count", 0) < MIN_MEMBER_COUNT:
        return False

    return True


def reject_candidate(
    candidate: Dict[str, Any],
    report: Dict[str, Any],
    thresholds: Optional[Dict[str, float]] = None,
) -> bool:
    """
    REJECT gate — fires if either condition holds:

      - grounding_score <= reject_threshold (default 0.2)
      - len(report.tensions) >= 3
    """
    thresholds = thresholds or {}
    reject_threshold = thresholds.get("reject", DEFAULT_REJECT_THRESHOLD)

    if report.get("grounding_score", 1.0) <= reject_threshold:
        return True

    if len(report.get("tensions", [])) >= MAX_TENSIONS_FOR_NONREJECT:
        return True

    return False


# ---------------------------------------------------------------------------
# (2) Batch evaluation
# ---------------------------------------------------------------------------

def _decide(
    candidate: Dict[str, Any],
    report: Dict[str, Any],
    thresholds: Optional[Dict[str, float]] = None,
) -> Dict[str, str]:
    """Return {'decision': str, 'rationale': str} for one candidate+report pair."""
    thresholds = thresholds or {}
    reject_threshold = thresholds.get("reject", DEFAULT_REJECT_THRESHOLD)

    tag = candidate.get("tag")
    grounding = report.get("grounding_score", 0.0)
    consistent = report.get("consistent")
    tensions = report.get("tensions", [])
    member_count = candidate.get("member_count", 0)

    # MATTER-FIRST-ARTIFACT is never accepted — investigate only.
    if tag == MATTER_FIRST_TAG:
        if reject_candidate(candidate, report, thresholds):
            return {
                "decision": DECISION_REJECT,
                "rationale": (
                    f"REJECT gate fired: grounding_score {grounding} <= "
                    f"reject_threshold {reject_threshold} or tensions >= 3 "
                    f"(tensions={len(tensions)})"
                ),
            }
        return {
            "decision": DECISION_DEFER,
            "rationale": (
                "MATTER-FIRST-ARTIFACT tag: never acceptable — "
                "deferred-for-investigation gate fired"
            ),
        }

    if accept_candidate(candidate, report, thresholds):
        accept_threshold = thresholds.get("accept", DEFAULT_ACCEPT_THRESHOLD)
        return {
            "decision": DECISION_ACCEPT,
            "rationale": (
                f"ACCEPT gate fired: grounding_score {grounding} >= "
                f"accept_threshold {accept_threshold}, consistent=True, "
                f"member_count {member_count} >= {MIN_MEMBER_COUNT}, "
                f"tag {tag!r} is a field tag"
            ),
        }

    if reject_candidate(candidate, report, thresholds):
        reasons = []
        if grounding <= reject_threshold:
            reasons.append(
                f"grounding_score {grounding} <= reject_threshold {reject_threshold}"
            )
        if len(tensions) >= MAX_TENSIONS_FOR_NONREJECT:
            reasons.append(f"tensions count {len(tensions)} >= {MAX_TENSIONS_FOR_NONREJECT}")
        return {
            "decision": DECISION_REJECT,
            "rationale": "REJECT gate fired: " + " OR ".join(reasons),
        }

    # DEFER — explain which accept conditions failed.
    accept_threshold = thresholds.get("accept", DEFAULT_ACCEPT_THRESHOLD)
    blockers = []
    if grounding < accept_threshold:
        blockers.append(f"grounding_score {grounding} < accept_threshold {accept_threshold}")
    if consistent is not True:
        blockers.append("consistent is not True")
    if member_count < MIN_MEMBER_COUNT:
        blockers.append(f"member_count {member_count} < {MIN_MEMBER_COUNT}")
    if tag not in FIELD_TAGS:
        blockers.append(f"tag {tag!r} not in {sorted(FIELD_TAGS)}")
    return {
        "decision": DECISION_DEFER,
        "rationale": "DEFER: no gate fired fully — " + "; ".join(blockers),
    }


def evaluate_candidates(
    candidates: List[Dict[str, Any]],
    consequence_reports: List[Dict[str, Any]],
    thresholds: Optional[Dict[str, float]] = None,
) -> Dict[str, List[Dict[str, Any]]]:
    """
    Evaluate all candidates against their consequence reports.

    `candidates` and `consequence_reports` are aligned by index.

    Returns {'accepted': [...], 'rejected': [...], 'deferred': [...]} where each
    entry is the candidate dict annotated with 'decision' and 'rationale'.
    """
    if len(candidates) != len(consequence_reports):
        raise ValueError(
            f"candidates ({len(candidates)}) and consequence_reports "
            f"({len(consequence_reports)}) must have equal length"
        )

    accepted: List[Dict[str, Any]] = []
    rejected: List[Dict[str, Any]] = []
    deferred: List[Dict[str, Any]] = []

    for candidate, report in zip(candidates, consequence_reports):
        outcome = _decide(candidate, report, thresholds)
        annotated = dict(candidate)
        annotated["decision"] = outcome["decision"]
        annotated["rationale"] = outcome["rationale"]

        if outcome["decision"] == DECISION_ACCEPT:
            accepted.append(annotated)
        elif outcome["decision"] == DECISION_REJECT:
            rejected.append(annotated)
        else:
            deferred.append(annotated)

    return {"accepted": accepted, "rejected": rejected, "deferred": deferred}


# ---------------------------------------------------------------------------
# (5) Convergence report
# ---------------------------------------------------------------------------

def build_convergence_report(
    run_id: str,
    evaluations: Dict[str, List[Dict[str, Any]]],
    cycles_run: int,
    stop_reason: str,
    dry_run: bool,
) -> Dict[str, Any]:
    """
    Build the final convergence report for a Rubedo run.

    `canon_mutated` is hard-asserted False — this module has no canon write path,
    so the flag can never be True. If a caller somehow passes mutated state the
    assertion will surface it immediately.
    """
    accepted = evaluations.get("accepted", [])
    rejected = evaluations.get("rejected", [])
    deferred = evaluations.get("deferred", [])

    accepted_count = len(accepted)
    rejected_count = len(rejected)
    deferred_count = len(deferred)

    if accepted_count >= 1:
        outcome = "converged"
    elif deferred_count >= 1 and accepted_count == 0:
        outcome = "deferred"
    else:
        outcome = "stopped"

    notes: List[str] = []
    if outcome == "converged":
        notes.append(
            f"{accepted_count} candidate(s) accepted — loop may terminate with field-grounded synthesis."
        )
    elif outcome == "deferred":
        notes.append(
            f"0 accepted, {deferred_count} deferred — candidates held for further investigation."
        )
    else:
        notes.append(
            f"0 accepted, 0 deferred, {rejected_count} rejected — loop stopped with no viable candidates."
        )
    if dry_run:
        notes.append("dry_run=True: no canon writes attempted or permitted.")
    notes.append("canon_mutated=False: Rubedo never mutates canon — assertion enforced at report build.")

    report = {
        "run_id": run_id,
        "outcome": outcome,
        "accepted_count": accepted_count,
        "rejected_count": rejected_count,
        "deferred_count": deferred_count,
        "cycles_run": cycles_run,
        "stop_reason": stop_reason,
        "dry_run": dry_run,
        "canon_mutated": False,
        "notes": notes,
    }

    # Hard assert: canon mutation is structurally impossible from this module.
    assert report["canon_mutated"] is False, (
        "Rubedo invariant violated: canon_mutated must always be False"
    )

    return report


# ---------------------------------------------------------------------------
# (7) Demo
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import json

    demo_candidates = [
        {
            "id": "cand-001",
            "statement": "The field shapes matter through resonance coherence.",
            "tag": "DERIVED-FROM-FIELD",
            "provenance": ["session-042", "ether-first-axiom"],
            "member_count": 3,
            "phase": "citrinitas",
        },
        {
            "id": "cand-002",
            "statement": "Ambient noise correlates with field fluctuations.",
            "tag": "FIELD-FACET",
            "provenance": ["session-017"],
            "member_count": 2,
            "phase": "citrinitas",
        },
        {
            "id": "cand-003",
            "statement": "Partial coherence observed under weak resonance conditions.",
            "tag": "FIELD-FACET",
            "provenance": ["session-055"],
            "member_count": 2,
            "phase": "citrinitas",
        },
        {
            "id": "cand-004",
            "statement": "The field emerges from matter under pressure.",
            "tag": "MATTER-FIRST-ARTIFACT",
            "provenance": ["session-099"],
            "member_count": 4,
            "phase": "citrinitas",
        },
    ]

    demo_reports = [
        # cand-001: ACCEPT — grounding 0.9, consistent, 3 members, field tag
        {"consistent": True, "supports": ["axiom-1"], "tensions": [], "grounding_score": 0.9},
        # cand-002: REJECT — grounding 0.1 <= reject_threshold 0.2
        {"consistent": True, "supports": [], "tensions": [], "grounding_score": 0.1},
        # cand-003: DEFER — grounding 0.5 between reject and accept thresholds
        {"consistent": True, "supports": [], "tensions": [], "grounding_score": 0.5},
        # cand-004: DEFER — MATTER-FIRST-ARTIFACT, never accepted despite 0.9 grounding
        {"consistent": True, "supports": [], "tensions": [], "grounding_score": 0.9},
    ]

    print("=" * 72)
    print("RUBEDO — Ether-First Alchemical Autoresearch Loop · Acceptance Phase")
    print("=" * 72)

    evaluations = evaluate_candidates(demo_candidates, demo_reports)

    for bucket in ("accepted", "rejected", "deferred"):
        entries = evaluations[bucket]
        print(f"\n[{bucket.upper()}] ({len(entries)} candidate(s))")
        for entry in entries:
            print(f"  id       : {entry['id']}")
            print(f"  tag      : {entry['tag']}")
            print(f"  decision : {entry['decision']}")
            print(f"  rationale: {entry['rationale']}")
            print()

    report = build_convergence_report(
        run_id="rubedo-demo-001",
        evaluations=evaluations,
        cycles_run=1,
        stop_reason=STOP_REASON_CONVERGED,
        dry_run=True,
    )

    print("-" * 72)
    print("CONVERGENCE REPORT")
    print("-" * 72)
    print(json.dumps(report, indent=2))

    # Verify success criteria inline.
    print("\n" + "=" * 72)
    print("SUCCESS CRITERIA CHECK")
    print("=" * 72)
    checks = [
        ("cand-001 accepted (grounding 0.9, consistent, 3 members, DERIVED-FROM-FIELD)",
         evaluations["accepted"][0]["id"] == "cand-001"),
        ("cand-002 rejected (grounding 0.1 <= 0.2)",
         evaluations["rejected"][0]["id"] == "cand-002"),
        ("cand-003 deferred (grounding 0.5 in no-gate zone)",
         any(e["id"] == "cand-003" for e in evaluations["deferred"])),
        ("cand-004 deferred — MATTER-FIRST-ARTIFACT never accepted (grounding 0.9)",
         any(e["id"] == "cand-004" for e in evaluations["deferred"])),
        ("canon_mutated is False in report", report["canon_mutated"] is False),
        ("outcome is 'converged' (>= 1 accepted)", report["outcome"] == "converged"),
    ]
    all_pass = True
    for label, passed in checks:
        status = "PASS" if passed else "FAIL"
        print(f"  [{status}] {label}")
        if not passed:
            all_pass = False
    print(f"\nOverall: {'ALL CHECKS PASSED' if all_pass else 'FAILURES DETECTED'}")
